### ISSUE TITLE
Test failure in Germany / Youtube says: Unfortunately, this video is not available in your country because it could contain music, for which we could not agree on conditions of use with GEMA.

### ISSUE THREAD

**Issue by mrueg** [mps-youtube/pafy#103]
Can you switch to another youtube video to be used in the tests please? 
This one is not working in Germany because of https://en.wikipedia.org/wiki/Blocking_of_YouTube_videos_in_Germany

```
 * python3_3: running distutils-r1_run_phase python_test
..E.............FF
======================================================================
ERROR: Use meta argument to generate filename.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pafy-0.3.74/work/pafy-0.3.74/tests/test.py", line 98, in test_generate_filename_with_meta
    p = pafy.new('jrNLsC_Y9Oo', size=True)
  File "/var/tmp/portage/dev-python/pafy-0.3.74/work/pafy-0.3.74/pafy/pafy.py", line 145, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/var/tmp/portage/dev-python/pafy-0.3.74/work/pafy-0.3.74/pafy/pafy.py", line 1076, in __init__
    self.fetch_basic()
  File "/var/tmp/portage/dev-python/pafy-0.3.74/work/pafy-0.3.74/pafy/pafy.py", line 1091, in fetch_basic
    self._fetch_basic()
  File "/var/tmp/portage/dev-python/pafy-0.3.74/work/pafy-0.3.74/pafy/pafy.py", line 1126, in _fetch_basic
    allinfo = get_video_info(self.videoid, newurl=info_url)
  File "/var/tmp/portage/dev-python/pafy-0.3.74/work/pafy-0.3.74/pafy/pafy.py", line 167, in get_video_info
    raise IOError("Youtube says: %s [%s]" % (reason, video_id))
nose.proxy.OSError: Youtube says: Unfortunately, this video is not available in your country because it could contain music, for which we could not agree on conditions of use with GEMA. [jrNLsC_Y9Oo]
-------------------- >> begin captured logging << --------------------
root: DEBUG: encoding unknown
root: DEBUG: Fetched video info
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: Test for expected number of streams.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pafy-0.3.74/work/pafy-0.3.74/tests/test.py", line 213, in test_streams_exist
    self.assertEqual(video['all streams'], len(paf.allstreams))
AssertionError: 27 != 30

======================================================================
FAIL: Test video properties.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pafy-0.3.74/work/pafy-0.3.74/tests/test.py", line 198, in test_video_properties
    video['description'])
nose.proxy.AssertionError: '17068ef10e9514337edd4dc42fa07afc99c9b9b7' != '72bfd9472e59a8f48b83af36197ebcf5d2227609'
- 17068ef10e9514337edd4dc42fa07afc99c9b9b7
+ 72bfd9472e59a8f48b83af36197ebcf5d2227609

-------------------- >> begin captured logging << --------------------
root: DEBUG: charset: application/json; charset=UTF-8
root: DEBUG: Fetched video gdata
root: DEBUG: charset: application/json; charset=UTF-8
root: DEBUG: charset: application/json; charset=UTF-8
root: DEBUG: Fetched video gdata
root: DEBUG: charset: application/json; charset=UTF-8
root: DEBUG: charset: application/json; charset=UTF-8
root: DEBUG: Fetched video gdata
root: DEBUG: charset: application/json; charset=UTF-8
root: DEBUG: charset: application/json; charset=UTF-8
root: DEBUG: Fetched video gdata
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 18 tests in 35.489s

FAILED (errors=1, failures=2)
```

**Comment by ids1024** [comment]
I'm on vacation now, but I will fix this when I get back.Thanks for noticing this.

**Comment by mrueg** [comment]
@ids1024  friendly ping? :)

**Comment by ids1024** [comment]
I will fix this before the next release. There are currently several other test failures to deal with as well...

**Comment by ctarjan** [comment]
An error has been discovered in video conversion of Japan .


    print str(t.encode('euc-kr'))
UnicodeEncodeError: 'euc_kr' codec can't encode character u'\u273f' in position 14: illegal multibyte sequence
>>> 

    print str(t.encode('euc-kr'))
UnicodeEncodeError: 'euc_kr' codec can't encode character u'\u2013' in position 21: illegal multibyte sequence
>>>
