### ISSUE TITLE
Traceback on 'Ls1OYn_xGzM'

### ISSUE THREAD

**Issue by bjauy** [mps-youtube/pafy#112]
Happened both in mps-youtube and ytdl, url is https://youtu.be/Ls1OYn_xGzM

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 145, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 1076, in __init__
    self.fetch_basic()
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 1102, in fetch_basic
    smaps, js_url, funcs, dashurl = get_js_sm(self.videoid)
  File "/usr/lib/python3.4/site-packages/pafy/pafy.py", line 692, in get_js_sm
    dash_url = stream_info['dashmpd']
KeyError: 'dashmpd'
```

Pafy version - 0.3.74

**Comment by ids1024** [comment]
I think that is fixed in git due to #109, which replaced the stream code (where that error is being produced) with calls to youtube-dl.

**Comment by johtso** [comment]
I'm still getting this problem with pafy 0.5.0

**Comment by ids1024** [comment]
@johtso Do you have youtube-dl installed?

**Comment by johtso** [comment]
ah, didn't realise it wasn't installed as a dependency, cheers!

**Comment by sunnytambi** [comment]
Thanks ids1024. Was missing just that.

**Comment by ritiek** [comment]
I'll close this as installing youtube-dl seems to have fixed the problem.
