### ISSUE TITLE
Some Youtube stream is not working

### ISSUE THREAD

**Issue by winstonma** [mps-youtube/pafy#119]
Hi,

First of all I am running pafy 0.3.76 because the App Engine doesn't support ctype and ssl which is required by 0.4.1.

After installing pafy, I tried to view the stream detail by the following command "ytdl -i cjYnyD3mUpc" which is my own video but it returns the following error:
> Traceback (most recent call last):
  File "/usr/local/bin/ytdl", line 194, in <module>
    main()
  File "/usr/local/bin/ytdl", line 136, in main
    vid = pafy.new(args.url)
  File "/Library/Python/2.7/site-packages/pafy/pafy.py", line 145, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "/Library/Python/2.7/site-packages/pafy/pafy.py", line 1085, in __init__
    self.fetch_basic()
  File "/Library/Python/2.7/site-packages/pafy/pafy.py", line 1128, in fetch_basic
    self.dash = _extract_dash(self._dashurl)
  File "/Library/Python/2.7/site-packages/pafy/pafy.py", line 322, in _extract_dash
    size = baseurl.attrib["%scontentLength" % ytns]
KeyError: u'{http://youtube.com/yt/2012/10/10}contentLength'

Since I never have this issue I am not sure if the problem is caused by the stream or papy? Thanks in advance

**Comment by ids1024** [comment]
Fixed in a0b76857a732a90cb065997496aa99339c34e947.
