### ISSUE TITLE
pafy Errors : KeyError: u'tags'

### ISSUE THREAD

**Issue by wdfsinap** [mps-youtube/pafy#122]
#!/usr/bin/python
import pafy
import requests
id ='rLGFr8OF5Pc'
d = pafy.new("https://www.youtube.com/watch?v="+id)
print d

I use Python 2.7 to test the Pafy. when I run on my server. I got the error
Traceback (most recent call last):
  File "t.py", line 8, in <module>
    print d
  File "/usr/local/lib/python2.7/site-packages/pafy/pafy.py", line 644, in __repr__
    keywords = ", ".join(self.keywords)
  File "/usr/local/lib/python2.7/site-packages/pafy/pafy.py", line 781, in keywords
    self._fetch_gdata()
  File "/usr/local/lib/python2.7/site-packages/pafy/pafy.py", line 621, in _fetch_gdata
    self._keywords = [uni(i) for i in snippet['tags']]
KeyError: u'tags'

when I run it on my local computer, I get the result:
Title: 中港台電話騙案告破 254疑犯從印柬押回國
Author: Chi Channel
ID: rLGFr8OF5Pc
Duration: 00:01:46
Rating: 0.0
Views: 324
Thumbnail: http://i.ytimg.com/vi/rLGFr8OF5Pc/default.jpg
Keywords: 
[Finished in 0.9s]

I don't know what's wrong. can you help me to fix the problem?
thanks

**Comment by ids1024** [comment]
Already fixed in git in commit f5fc3f57
