### ISSUE TITLE
AttributeError: 'InternPafy' object has no attribute 'fetch_basic'

### ISSUE THREAD

**Issue by adammenges** [mps-youtube/pafy#135]
```
⇒  py youtube.py
WARNING:root:pafy: youtube-dl not found; falling back to internal backend. This is not as well maintained as the youtube-dl backend. To hide this message, set the environmental variable PAFY_BACKEND to "internal".
Lecture 1.1 — Why do we need machine learning  [Neural Networks for Machine Learning]
Traceback (most recent call last):
  File "youtube.py", line 24, in <module>
    best = p.getbest(preftype="mp4")
  File "/usr/local/lib/python2.7/site-packages/pafy/backend_shared.py", line 381, in getbest
    return self._getbest(preftype, ftypestrict, vidonly=False)
  File "/usr/local/lib/python2.7/site-packages/pafy/backend_shared.py", line 343, in _getbest
    streams = self.videostreams if vidonly else self.streams
  File "/usr/local/lib/python2.7/site-packages/pafy/backend_shared.py", line 159, in streams
    self._process_streams()
  File "/usr/local/lib/python2.7/site-packages/pafy/backend_internal.py", line 139, in _process_streams
    self.fetch_basic()
AttributeError: 'InternPafy' object has no attribute 'fetch_basic'
```

On lastest in pip. Python 2.7.x. OSX 10.11.

Also happens if I clone master here and build.

**Comment by adammenges** [comment]
``` python
import pafy
import os

# playlist_url = raw_input("What's the URL of the playlist? ")
playlist_url = "https://www.youtube.com/playlist?list=PLoRl3Ht4JOcdU872GhiYWf6jwrk_SNhz9"
playlist = pafy.get_playlist(playlist_url)
videos = playlist['items']
directory = "./" + playlist['title']

if not os.path.exists(directory):
    os.makedirs(directory)

for video in videos:
  p = video['pafy']
  print(p.title)
  best = p.getbest(preftype="mp4")
  filepath = directory + "/" + best.title + "." + best.extension
  best.download(filepath=filepath)

print("Done.")
```

**Comment by ids1024** [comment]
Ok, this is now fixed in 79afcc532a3104474e87f4e000701a875ec15db6, but then there is a different error, which is slightly harder to solve.

You should probably install youtube-dl (such as with `pip install youtube_dl`), so that pafy will use that as a back-end instead of the internal one. It is the recommended back-end. The internal one is maintained for reasons mentioned in #110.

**Comment by ids1024** [comment]
https://github.com/mps-youtube/pafy/commit/a0b76857a732a90cb065997496aa99339c34e947 fixed the second error, so now this should work.

**Comment by adammenges** [comment]
Danke danke
