### ISSUE TITLE
Import fails after pip installation

### ISSUE THREAD

**Issue by Thrasi** [mps-youtube/pafy#142]
I ran:

$ sudo pip install pafy
$ ipython
> import pafy
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-4633f5d85f78> in <module>()
----> 1 import pafy

pafy.py in <module>()

ValueError: Attempted relative import in non-package

running on ubuntu.

**Comment by ids1024** [comment]
Is that python 2 or 3?

Not much has changed since the last release, but you could try installing the git version with `sudo pip install --upgrade https://github.com/mps-youtube/pafy/archive/develop.zip`.

**Comment by DannyDannyDanny** [comment]
@ids1024 I'n on python 3 - and not much success on this one. I have same issue as OP.

Here's the return when trying 

```
Collecting https://github.com/mps-youtube/pafy/archive/develop.zip
  Downloading https://github.com/mps-youtube/pafy/archive/develop.zip
     / 81kB 413kB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "/private/tmp/pip-req-build-ze7v__qc/pafy/pafy.py", line 48, in <module>
        import youtube_dl
    ModuleNotFoundError: No module named 'youtube_dl'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-ze7v__qc/setup.py", line 13, in <module>
        from pafy import __version__
      File "/private/tmp/pip-req-build-ze7v__qc/pafy/__init__.py", line 7, in <module>
        from .pafy import new
      File "/private/tmp/pip-req-build-ze7v__qc/pafy/pafy.py", line 52, in <module>
        "pafy: youtube-dl not found; you can use the internal backend by "
    ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-ze7v__qc/
```

**Comment by DannyDannyDanny** [comment]
This fixed everything 👍 
```
sudo pip install --upgrade youtube_dl pafy
```
