### ISSUE TITLE
Error when I try to get the category and/or description

### ISSUE THREAD

**Issue by ghost** [mps-youtube/pafy#152]
It is working very well for getting the majority of the parameters and downloading, with the exceptions of category and description. I tried with more than 10 videos, and checked for all of them to have a category and description. I use Python 3.

The error:

Traceback (most recent call last):
  File "d:\devenv\python\Lib\urllib\request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "d:\devenv\python\Lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "d:\devenv\python\Lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "d:\devenv\python\Lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "d:\devenv\python\Lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "d:\devenv\python\Lib\http\client.py", line 854, in send
    self.connect()
  File "d:\devenv\python\Lib\http\client.py", line 1237, in connect
    server_hostname=server_hostname)
  File "d:\devenv\python\Lib\ssl.py", line 376, in wrap_socket
    _context=self)
  File "d:\devenv\python\Lib\ssl.py", line 747, in __init__
    self.do_handshake()
  File "d:\devenv\python\Lib\ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "d:\devenv\python\Lib\ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

File "..Learn/Youtube/download.py", line 7, in <module>
    print(v.description)
  File "D:\DevEnv\Python Enviroments\DM\lib\site-packages\pafy\backend_shared.py", line 291, in description
    self._fetch_gdata()
  File "D:\DevEnv\Python Enviroments\DM\lib\site-packages\pafy\backend_internal.py", line 117, in _fetch_gdata
    item = self._get_video_gdata(self.videoid)['items'][0]
  File "D:\DevEnv\Python Enviroments\DM\lib\site-packages\pafy\backend_shared.py", line 122, in _get_video_gdata
    gdata = call_gdata('videos', query)
  File "D:\DevEnv\Python Enviroments\DM\lib\site-packages\pafy\util.py", line 27, in call_gdata
    data = g.opener.open(url).read().decode('utf-8')
  File "d:\devenv\python\Lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "d:\devenv\python\Lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "d:\devenv\python\Lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "d:\devenv\python\Lib\urllib\request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "d:\devenv\python\Lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)>

**Comment by ids1024** [comment]
That is odd. What OS/Distro are you using?

**Comment by PaulDevI** [comment]
Windows 7, 64 bit.

**Comment by ids1024** [comment]
It's showing an ssl error. Is https working fine in your python install, outside of pafy?

**Comment by PaulDevI** [comment]
I have a script that use https to login on an website a gather data, and is working with no issues.

Pafy works well with the other attributes(using https), I have this error only when I try to get description and category, so I don't think SSL alone is the culprit. What this methods do that is different compared to the others ?

When I use directly the private method, for example "_description" I received no value, and no error.   If I use the description method (as in documentation) I receive the error above. 

I thought youtube changed something and the private method can't get the description, and send to normal method an error.

How can I test further to see exactly what is happening ?

**Comment by ids1024** [comment]
> What this methods do that is different compared to the others ?

Ah, yes, there is. Those methods use the gdata api, so that must be what you are having trouble with. If so, `.published` should also fail, so you can try that.

That said, I don't really know why it would be an issue.

> When I use directly the private method, for example "_description" I received no value, and no error

That is not a method; it is just the variable used to store the value after it is retrieved. The public methods like `.description` test if the internal variable is set, and if it is not they call the function to retrieve its value.

**Comment by ritiek** [comment]
I'll be closing this due to inactivity. If someone has this issue in the future, feel free to leave a comment here or open a new issue!
