### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by spvkgn** [mps-youtube/pafy#160]
Could anyone explain what causes this error and how to fix it?
```
~ $ mpsyt --debug
mpsyt version      : 0.2.7.1
   notes           : released 6 July 2016
pafy version       : 0.5.2 (youtube-dl backend)
youtube-dl version : 2016.11.14.1
Python version     : 3.2.3 (default, Jun 18 2015, 21:46:42) 
[GCC 4.6.3]
Processor          : i686
Machine type       : i686
Architecture       : 32bit, ELF
Platform           : Linux-3.13.0-77-generic-i686-with-LinuxMint-13-maya
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /home/pavel/.config/mps-youtube
env:TERM           : screen-256color
env:SHELL          : /bin/bash
env:LANG           : ru_RU.UTF-8
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/pafy/util.py", line 27, in call_gdata
    data = g.opener.open(url).read().decode('utf-8')
  File "/usr/lib/python3.2/urllib/request.py", line 375, in open
    response = meth(req, response)
  File "/usr/lib/python3.2/urllib/request.py", line 487, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.2/urllib/request.py", line 413, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 347, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.2/urllib/request.py", line 495, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 7, in <module>
    from mps_youtube import main
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/init.py", line 58, in init
    cache.load()
  File "/usr/local/lib/python3.2/dist-packages/mps_youtube/cache.py", line 34, in load
    pafy.load_cache(cached['pafy'])
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 182, in load_cache
    set_categories(newcache.get('categories', {}))
  File "/usr/local/lib/python3.2/dist-packages/pafy/pafy.py", line 169, in set_categories
    catinfo = call_gdata('videoCategories', query)
  File "/usr/local/lib/python3.2/dist-packages/pafy/util.py", line 35, in call_gdata
    raise GdataError(errmsg)
pafy.util.GdataError: HTTP Error 403: Forbidden
```

**Comment by embryo10** [comment]
I also get a similar error.
I made a music player that can play YouTube links too.
Everything works OK until after some hours that the app is open (playing or not playing does not make any difference) eventually it will give me a `urllib2.URLError 'HTTP Error 403: Forbidden'` error.
Its with a different link every time.
After that, all the links I try give me the same error.
The only way to fix it is to restart the application.
After that I can have the app open for some more hours before the next error...
I found [this issue](https://github.com/rg3/youtube-dl/issues/6451) at youtube-dl repository but I could not find a way to implement their solution (--no-cache-dir) with pafy.
I don't even know that it will solve my issue, but hey, I have to try that too.
I'm willing to test any solutions since its nearly impossible for someone else to replicate it.

**Comment by embryo10** [comment]
Tried to remove the youtube-dl cache manually when the error occurred, but that didn't fixed it either.
After the first error, no link works anymore until I restart the program.
The next try will be to try and reload all the modules that pafy initially loads:
```Python
pafy.new = reload(pafy.new)
pafy.set_api_key = reload(pafy.set_api_key)
pafy.load_cache = reload(pafy.load_cache)
pafy.dump_cache = reload(pafy.dump_cache)
pafy.get_categoryname = reload(pafy.get_categoryname)
pafy.backend = reload(pafy.backend)
pafy.GdataError = reload(pafy.GdataError)
pafy.call_gdata = reload(pafy.call_gdata)
pafy.get_playlist = reload(pafy.get_playlist)
pafy.get_playlist2 = reload(pafy.get_playlist2)
```
I 'll report the results here...

**Comment by embryo10** [comment]
SOLVED
After all this time, I realized that I get this message only when a pafy object is older than ~ 6 hours.
So the solution is really easy.
I just re-create the pafy object ;o)
Thats all!!!

**Comment by sameerkumar18** [comment]
I'm still facing a similar issue! On some videos, while serving on Django I get 403 error when I open the m4a audiostream URL
Here is how I am using pafy at the moment - 
```
import pafy
def converter_pafy(video_id):
    p = pafy.new(video_id)
    url = p.audiostreams[2].url

    return str(url) 
```

On some videos, the function returns the URL normally but when I open the URL, I get a 403 like this video_id 7mWQ38SpEf8. 
I tried few things, but still failed - 
1) ` del sys.module["pafy"], del sys.module["youtube_dl"] `
2) ` del p` (p is the pafy object) `

Can someone please help me out? What am I doing wrong? 
Any suggestions @embryo10 @spvkgn ?

Thanks
