### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ConnyOnny** [mps-youtube/pafy#165]
Using pip from current Ubuntu LTS 16.04.1

pafy's utility.py tries to find out if the stdout is capable of UTF-8 handling, but its output is redirected to /dev/null by pip, so `sys.stdout.encoding` is `None`, but this case is not handled. I don't know how anybody else installs pafy. I think this should break the installation for everyone using pip on anything else but Windows (because this case is handled before as an early returning `or`).

```
$ sudo pip install pafy
The directory '/home/c/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/c/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pafy
  Downloading pafy-0.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xHjJ7F/pafy/setup.py", line 13, in <module>
        from pafy import __version__
      File "pafy/__init__.py", line 7, in <module>
        from .pafy import new
      File "pafy/pafy.py", line 40, in <module>
        from .util import call_gdata
      File "pafy/util.py", line 18, in <module>
        not_utf8_environment = mswin or "UTF-8" not in sys.stdout.encoding
    TypeError: argument of type 'NoneType' is not iterable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xHjJ7F/pafy/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by ConnyOnny** [comment]
So, I just installed the previous version for now:
```
$ sudo pip install pafy==0.5.2
The directory '/home/c/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/c/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pafy==0.5.2
  Downloading pafy-0.5.2-py2.py3-none-any.whl
Installing collected packages: pafy
Successfully installed pafy-0.5.2
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by ids1024** [comment]
I've pushed a new release with a fix. Tell me if it works.

**Comment by ConnyOnny** [comment]
Wow, thank you for the quick reply! It works. 👍
