### ISSUE TITLE
Erroe while downloading pafy.new("https://youtu.be/pRpeEdMmmQ0")

### ISSUE THREAD

**Issue by anujdecoder** [mps-youtube/pafy#167]
import pafy
v = pafy.new("https://youtu.be/pRpeEdMmmQ0")
s = v.getbest()
print("Size is %s" % s.get_filesize())
filename = s.download()

This code is working for other videos.
Following errors are reported
Traceback (most recent call last):
  File "F:/DB/demo.py", line 2, in <module>
    v = pafy.new("https://youtu.be/pRpeEdMmmQ0")
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pafy\pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pafy\backend_internal.py", line 42, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pafy\backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pafy\backend_internal.py", line 92, in _fetch_basic
    smaps, js_url, mainfunc = get_js_sm(watchinfo, self.callback)
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pafy\backend_internal.py", line 430, in get_js_sm
    dbg_ref="javascript", file_prefix="js-")
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pafy\backend_internal.py", line 367, in fetch_cached
    data = fetch_decode(url, "utf8")  # unicode
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pafy\pafy.py", line 65, in fetch_decode
    req = g.opener.open(url)
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 511, in open
    req = Request(fullurl, data)
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 329, in __init__
    self.full_url = url
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 355, in full_url
    self._parse()
  File "C:\Users\Anuj Gupta\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 384, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflVlxFvV/base.js'

**Comment by ids1024** [comment]
Install youtube-dl with `pip3 install youtube-dl`.
