### ISSUE TITLE
My code gives me errors

### ISSUE THREAD

**Issue by OriginalOmarion** [mps-youtube/pafy#188]
import pafy
url = "https://www.youtube.com/watch?v=pcamjcoRmrQ"
video = pafy.new(url)

This code gives me these errors:

 File "C:/_Programming/Python/Programs0/AudioPlayer/AudioPlayer.py", line 3, in <module>
    video = pafy.new(url)

  File "C:\_Programming\Python\PythonInstall\lib\site-packages\pafy\pafy.py", line 125, in new
    return Pafy(url, basic, gdata, signature, size, callback, ydl_opts)

  File "C:\_Programming\Python\PythonInstall\lib\site-packages\pafy\backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)

  File "C:\_Programming\Python\PythonInstall\lib\site-packages\pafy\backend_shared.py", line 95, in __init__
    self._fetch_basic()

  File "C:\_Programming\Python\PythonInstall\lib\site-packages\pafy\backend_youtube_dl.py", line 53, in _fetch_basic
    self._category = self._ydl_info['categories'][0]

TypeError: 'NoneType' object is not subscriptable

**Comment by ritiek** [comment]
That video seems to work fine for me. You might have luck updating `youtube-dl`.

**Comment by strafe** [comment]
@ritiek I'm using Python `3.5.3`, pafy `0.5.3.1` and youtube_dl `2017.12.2` on Debian `9.2`.

When I run a simple example that's [shown in the documentation](http://pythonhosted.org/pafy/#Pafy.Pafy.allstreams) it errors out in the same way @OriginalOmarion has shown:
```Python
import pafy

v = pafy.new("0_Lt7WZ9mE4")
v.audiostreams
```
```BASH
user@server:~/python/pafy$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    v = pafy.new("0_Lt7WZ9mE4")
  File "/home/user/.local/lib/python3.5/site-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/user/.local/lib/python3.5/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/pafy/backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "/home/user/.local/lib/python3.5/site-packages/pafy/backend_youtube_dl.py", line 38, in _fetch_basic
    self._ydl_info = ydl.extract_info(self.videoid, download=False)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 784, in extract_info
    ie_result = ie.extract(url)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 437, in extract
    ie_result = self._real_extract(url)
  File "/home/user/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1599, in _real_extract
    if 'token' not in video_info:
TypeError: argument of type 'NoneType' is not iterable
user@server:~/python/pafy$
```
<hr>

I'm also finding it quite strange to deal with playlists in general since each item inside a playlist is a `pafy.YtdlPafy` instead of just a normal `pafy.Pafy`.

**Comment by ritiek** [comment]
I'll close this as this issue is no longer relevant for latest releases of youtube-dl and pafy. If someone still has this issue, feel free to comment here or open a new issue!

**Comment by logusivam** [comment]
Type error builtin function or method object is not subscrptable
