### ISSUE TITLE
Make possible to download "not for all" labeled videos

### ISSUE THREAD

**Issue by yperevera** [mps-youtube/pafy#189]
Hi, everyone!

I get an error when trying to download the video that has "not for all" label:

#---- start --------
Traceback (most recent call last):
  File "C:\Users\pc\Dropbox\Python\DEV\YouTubeDownloader\youtubeDownloader_v.1.py", line 24, in <module>
    video = pafy.new(url)
  File "C:\Python34\lib\site-packages\pafy\pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "C:\Python34\lib\site-packages\pafy\backend_internal.py", line 42, in __init__
    super(InternPafy, self).__init__(*args, **kwargs)
  File "C:\Python34\lib\site-packages\pafy\backend_shared.py", line 96, in __init__
    self._fetch_basic()
  File "C:\Python34\lib\site-packages\pafy\backend_internal.py", line 50, in _fetch_basic
    allinfo = get_video_info(self.videoid, self.callback)
  File "C:\Python34\lib\site-packages\pafy\backend_internal.py", line 278, in get_video_info
    raise IOError("Youtube says: %s [%s]" % (reason, video_id))
OSError: Youtube says: <a href="http://www.youtube.com/watch?v=X3f2SVFX4DM&feature=player_embedded" target="_blank">Перегляньте це відео на YouTube.</a> Власник відео вимкнув можливість відтворювати його на інших веб-сайтах. [X3f2SVFX4DM]
#---- end ---------

The reason is translated according to my location but it says that the YouTube video is not allowed for direct playback on embedded platforms and the privacy settings were set by the owner of the video this way.
But it is possible to download via Savefrom.net.
So it would be cool to implement such feature into your product.

Thanks!

**Comment by ritiek** [comment]
Do you have `youtube-dl` installed?

**Comment by yperevera** [comment]
ritiek, no. 
I installed `youtube-dl` and issue is not reproducing anymore.
Thank you for your help!
