### ISSUE TITLE
Release a new version on PyPI

### ISSUE THREAD

**Issue by ritiek** [mps-youtube/pafy#221]
After some few bug fixes and especially the merge of #203 which allows downloading video/audio at optimal download speeds, I think it might be a good idea to release a new version on PyPI.

**Comment by ng-0** [comment]
I think it definitely is:

```
Traceback (most recent call last):
  File "/usr/pkg/lib/python3.7/site-packages/pafy/util.py", line 34, in call_gdata
    data = g.opener.open(url).read().decode('utf-8')
  File "/usr/pkg/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/pkg/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/pkg/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/pkg/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/pkg/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/pkg/bin/mpsyt", line 11, in <module>
    load_entry_point('mps-youtube==0.2.8', 'console_scripts', 'mpsyt')()
  File "/usr/pkg/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/pkg/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/pkg/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/pkg/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/pkg/lib/python3.7/site-packages/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/usr/pkg/lib/python3.7/site-packages/mps_youtube/init.py", line 58, in init
    cache.load()
  File "/usr/pkg/lib/python3.7/site-packages/mps_youtube/cache.py", line 34, in load
    pafy.load_cache(cached['pafy'])
  File "/usr/pkg/lib/python3.7/site-packages/pafy/pafy.py", line 184, in load_cache
    set_categories(newcache.get('categories', {}))
  File "/usr/pkg/lib/python3.7/site-packages/pafy/pafy.py", line 171, in set_categories
    catinfo = call_gdata('videoCategories', query)
  File "/usr/pkg/lib/python3.7/site-packages/pafy/util.py", line 42, in call_gdata
    raise GdataError(errmsg)
pafy.util.GdataError: Youtube Error 403: The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.
```

Unless I have missed an update besides youtube-dl.

**Comment by gnojus** [comment]
Indeed

**Comment by ids1024** [comment]
Ah yeah, this should have been done a while ago.

@ritiek If you (or someone else who's a member of the mps-youtube GitHub org) would like, I can give you pyPI privileges for mps-youtube and pafy.

**Comment by ritiek** [comment]
@ids1024 Sounds good from my side. I'm also "ritiek" on PyPI in case it may ask for the username. However, I'm not as much active as I used to be so If someone else from the org can manage PyPI releases, that would be alright too.

**Comment by ids1024** [comment]
@ritiek I've added you as a maintainer for both on PyPI, and I've taken some time to [document](https://github.com/mps-youtube/mps-youtube/blob/develop/RELEASING.md) the (currently somewhat complicated) release process.

Hopefully the information in the document is helpful. I suppose some other setting need to be changed to allow creating Github releases and pushing to master? Hm...

**Comment by ritiek** [comment]
@ids1024 Thanks! The document indeed contains valuable insight on the release process.

> I suppose some other setting need to be changed to allow creating Github releases and pushing to master? Hm...

Seems like I can already publish releases for the mps-youtube org on GitHub. I'll hopefully get to prepare the next pafy release within a few days, I'll let you know just in case it requires additional priveleges.

**Comment by ritiek** [comment]
v0.5.5 is now released on PyPI and pafy can be upgraded to using:
```
$ pip install pafy -U
```
I'll close this.
