### ISSUE TITLE
youtube_dl "Error 403: Forbidden"

### ISSUE THREAD

**Issue by noembryo** [mps-youtube/pafy#264]
I was getting this error
```python
Traceback (most recent call last):
  File "secondary.py", line 1217, in process
  File "secondary.py", line 1272, in get_stream
  File "site-packages\pafy\backend_youtube_dl.py", line 183, in download
  File "site-packages\youtube_dl\downloader\common.py", line 366, in download
  File "site-packages\youtube_dl\downloader\http.py", line 341, in real_download
  File "site-packages\youtube_dl\downloader\http.py", line 109, in establish_connection
  File "site-packages\pafy\backend_youtube_dl.py", line 192, in urlopen
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 403: Forbidden
```
that was coming from `youtube_dl` and it was happening with all the urls I was trying to get.
It was happening with two of my apps. One that uses `pafy` and another that uses `youtube_dl` directly.
I opened an issue at their github and I was told to use the `--rm-cache-dir` switch to solve it.
Since I was using it as a library, I used
```python
with youtube_dl.YoutubeDL(opts) as ydl:
    try:
        ydl.cache.remove()
        ydl.download([url])
    except youtube_dl.utils.DownloadError as err:
        print(err)
```
and it was fixed.
The weird thing is that after that, it was fixed for my other app too.
I could not replicated it anymore with `pafy`.

So my problem is this.
Since I got some calls from some friends that use my `pafy` app, I would like to find a way to clear the `youtube_dl`'s cache if a problem like this occur.

Any ideas?
TIA

**Comment by noembryo** [comment]
I added the "clear cache" command inside the `try`/`except` of the `_fetch_basic` method in `backend_youtube_dl.py`
```python
        with youtube_dl.YoutubeDL(self._ydl_opts) as ydl:
            try:
                ydl.cache.remove()
                self._ydl_info = ydl.extract_info(self.videoid, download=False)
            # Turn into an IOError since that is what pafy previously raised
            except youtube_dl.utils.DownloadError as e:
                raise IOError(str(e).replace('YouTube said', 'Youtube says'))
```
I don't have a way to test it anymore (since everything works now) but perhaps it will do its job..

**Comment by kekfic** [comment]
@noembryo , thanks!  it worked for me.

**Comment by ritiek** [comment]
@noembryo Nice!

However, since
```python
>>> ydl.cache.remove()
```
deletes youtube-dl's cache directory, so invoking youtube-dl with:
```
$ youtube-dl --rm-cache-dir
```
should also fix this.

**Comment by noembryo** [comment]
@ritiek how can we invoke `youtube_dl` with the `--rm-cache-dir` from inside our script (using `youtube_dl` as a library)?

**Comment by noembryo** [comment]
@ritiek how can we invoke `youtube_dl` with the `--rm-cache-dir` from inside our script (using `youtube_dl` as a library)?

**Comment by ritiek** [comment]
@noembryo It's similar to how you did it in https://github.com/mps-youtube/pafy/issues/264#issuecomment-616873490:

```python
import youtube_dl

with youtube_dl.YoutubeDL({}) as ydl:
    ydl.cache.remove()
```
youtube-dl calls this same method `cache.remove()` internally when `--rm-cache-dir` has been passed on the command-line.

**Comment by noembryo** [comment]
A, OK, I thought that there was some mystical way.. ;o)
Should I create a PR for this?

**Comment by ritiek** [comment]
I don't think a PR for this would be a good idea. youtube-dl maintains this local cache to make future video fetches faster and pafy messing with this cache doesn't sound nice. By the way, I haven't tried but it should be possible to achieve the same behaviour as your changes in https://github.com/mps-youtube/pafy/issues/264#issuecomment-616873490 by passing `--no-cache-dir` flag to youtube-dl from pafy.

Also, I think youtube-dl messed up this one time with their cache. So while I'm not sure about this one and needs to be confirmed, but invoking youtube-dl to purge the cache directory once should prevent any future 403 errors. If I'm right on this one, IMO we should leave things as it is. Otherwise we might have to come up with something.

**Comment by noembryo** [comment]
Agree.
I will handle it from my code, and only if a problem arise, not with every call.
I hope that the guys @youtube_dl prevent any more errors...

**Comment by 0xbrayo** [comment]
@ritiek hope you will roll out that fix on spotdl soon

**Comment by pYr0x** [comment]
none of these things worked for me. 
here is a repl.it: https://repl.it/repls/FixedImmaterialDesignmethod
if the repl is not working, here is a gist: https://gist.github.com/pYr0x/11889d1a26e506563529c0d424dea0ff

its about this youtube-video ID: HC6vN-qd0TE

**Comment by noembryo** [comment]
Its working if you use `http` instead of `https`
e.g. `http://www.youtube.com/watch?v=HC6vN-qd0TE`

**Comment by pYr0x** [comment]
didn't worked for me: https://repl.it/repls/LittleThistleNet

**Comment by harshitsinghai77** [comment]
> ```python
> with youtube_dl.YoutubeDL({}) as ydl:
>     ydl.cache.remove()
> ```

This worked. Thanks.
