### ISSUE TITLE
KeyError: 'thumbnails'

### ISSUE THREAD

**Issue by kdziedzic66** [mps-youtube/pafy#268]
Ive started to use pafy about 2 weeks ago - everything has been working fine for me but today ( there were no changes in my code ) I have started to get the following error after calling ```pafy.new``` - here is full traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/ml-team/homes/krzysztof.dziedzic/virtualenvs/dsv_examples/lib/python3.6/site-packages/pafy/pafy.py", line 124, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts=ydl_opts)
  File "/mnt/ml-team/homes/krzysztof.dziedzic/virtualenvs/dsv_examples/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 31, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/mnt/ml-team/homes/krzysztof.dziedzic/virtualenvs/dsv_examples/lib/python3.6/site-packages/pafy/backend_shared.py", line 97, in __init__
    self._fetch_basic()
  File "/mnt/ml-team/homes/krzysztof.dziedzic/virtualenvs/dsv_examples/lib/python3.6/site-packages/pafy/backend_youtube_dl.py", line 57, in _fetch_basic
    self._bestthumb = self._ydl_info['thumbnails'][0]['url']
KeyError: 'thumbnails
```

**Comment by PlasmaPower** [comment]
This is due to https://github.com/ytdl-org/youtube-dl/issues/25676 though pafy probably shouldn't error completely if no thumbnail is found

**Comment by zhanwenchen** [comment]
Is there any fix? There's a commit on pafy that addresses it

**Comment by PlasmaPower** [comment]
It should work now if you update youtube-dl to the latest git version (not yet released), though I think pafy shouldn't completely error if it can't get the thumbnail.

**Comment by kdziedzic66** [comment]
youtube-dl fix has helped
