### ISSUE TITLE
pafy in android LogFile' object has no attribute 'encoding' 

### ISSUE THREAD

**Issue by Sahil-pixel** [mps-youtube/pafy#276]
Traceback (most recent call last):
I/python  ( 9349):    File "/home/sahil/app4/.buildozer/android/app/main.py", line 18, in <module>
I/python  ( 9349):    File "/home/sahil/app4/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ki/pafy/__init__.py", line 7, in <module>
I/python  ( 9349):    File "/home/sahil/app4/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ki/pafy/pafy.py", line 40, in <module>
I/python  ( 9349):    File "/home/sahil/app4/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/ki/pafy/util.py", line 18, in <module>
I/python  ( 9349):  AttributeError: **'LogFile' object has no attribute 'encoding'**
I/python  ( 9349): Python for android ended.
^Z

**Comment by dovahkinnn** [comment]
Same issue  pls help

**Comment by anupamkayal** [comment]
pip install pafy==0.5.1
Just download old version of pafy . In my case it is working

**Comment by Sahil-pixel** [comment]
In android os ?

**Comment by anupamkayal** [comment]
Hmm(yes) android os

**Comment by Sahil-pixel** [comment]
thanks  it is working .

**Comment by Sahil-pixel** [comment]
thanks it is working ...
