### ISSUE TITLE
video  - pIp9Qi6MnGI

### ISSUE THREAD

**Issue by meirl** [mps-youtube/pafy#36]
pafy 0.3.52
python 2.7

>>> pafy.new('pIp9Qi6MnGI')

Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    pafy.new('pIp9Qi6MnGI')
  File "build\bdist.win32\egg\pafy\pafy.py", line 129, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "build\bdist.win32\egg\pafy\pafy.py", line 824, in __init__
    self.fetch_basic()
  File "build\bdist.win32\egg\pafy\pafy.py", line 883, in fetch_basic
    self._process_streams()
  File "build\bdist.win32\egg\pafy\pafy.py", line 919, in _process_streams
    streams = [Stream(z, self) for z in self.sm]
  File "build\bdist.win32\egg\pafy\pafy.py", line 540, in __init__
    self._rawurl = sm['url']
KeyError: u'url'

**Comment by ids1024** [comment]
After merging #109, the youtube-dl function pafy calls gives an error message explaining this somewhat.

`youtube_dl.utils.DownloadError: ERROR: rtmpe downloads are not supported, see https://github.com/rg3/youtube-dl/issues/343 for
more information.`

I think I will call this "fixed". It now gives a more meaningful error message, and if it is fixed in youtube-dl at some point (if that is even possible), it should work in pafy too.

As stated in the error message, see rg3/youtube-dl#343 for more information and any progress that might be made in solving it.
