### ISSUE TITLE
getting 403 forbidden error when trying to get the metadata

### ISSUE THREAD

**Issue by ranjeetsinha13** [mps-youtube/pafy#84]
video = pafy.new(url) gives forbidden 403 error for most of the youtube video urls. Below is the stacktrace.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pafy.py", line 137, in new
    return Pafy(url, basic, gdata, signature, size, callback)
  File "pafy.py", line 1047, in __init__
    self.fetch_basic()
  File "pafy.py", line 1062, in fetch_basic
    self._fetch_basic()
  File "pafy.py", line 1096, in _fetch_basic
    allinfo = get_video_info(self.videoid, newurl=info_url)
  File "pafy.py", line 144, in get_video_info
    info = fetch_decode(url)  # bytes
  File "pafy.py", line 90, in fetch_decode
    req = g.opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by ids1024** [comment]
What specific videos?

**Comment by telekenetix** [comment]
I noticed this problem when using pythonanywhere.com/


I believe it was due to the fact that their free-tier has restrictions on what sites can be accessed.
